beholder/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from core.views import Index, Finder, Auth, GetUser, ShowUsers, ShowPosts, ShowTags, ShowPostsPerTag, \
    ShowConnectionsFromUser, ShowGraph, ShowNetworks, ShowPostsPerNetwork, ShowTagsPerUser, ShowPlaces, ShowTips

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^finder/', Finder.as_view()),
    url(r'^auth/', Auth.as_view()),
	url(r'^$', Index.as_view()),
    url(r'^users/(.+)/$', GetUser.as_view(), name='User_Detail'),
    url(r'^networks/$', ShowNetworks.as_view(), name='Networks'),
    url(r'^networks/(.+)/$', ShowPostsPerNetwork.as_view(), name='Networks_Detail'),
    url(r'^users/$', ShowUsers.as_view(), name="All_Users"),
    url(r'^posts/$', ShowPosts.as_view(), name="All_Posts"),
    url(r'^tags/$', ShowTags.as_view(), name="All_Tags"),
    url(r'^tags/from/(.+)/$', ShowTagsPerUser.as_view(), name='Tags_Per_User_Detail'),
    url(r'^tags/(.+)/$', ShowPostsPerTag.as_view(), name='Posts_Per_Tag_Detail'),
    url(r'^places/$', ShowPlaces.as_view(), name='All_Places'),
    url(r'^places/(.+)/$', ShowTips.as_view(), name='Tips_Per_Place'),
    url(r'^connections/from/(.+)/$', ShowConnectionsFromUser.as_view(), name='Connections_From_User'),
    url(r'^graph/$', ShowGraph.as_view(), name='Global_Graph'),
]

beholder/apps/core/models.py
from django.db import models

# Create your models here.
class Person(models.Model):
    login = models.TextField(max_length=30, unique=True)
    name = models.TextField(max_length=80)
    profile_picture = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return self.login

class Post(models.Model):
    id = models.TextField(max_length=255, primary_key=True, unique=True)
    author = models.ForeignKey(Person)
    dateOfCreation = models.DateTimeField()
    photo = models.CharField(max_length=255)
    text = models.CharField(max_length=255)
    latitude = models.FloatField()
    longitude = models.FloatField()
    network = models.CharField(max_length=255) # E.g. Twitter / Instagram

    def __str__(self):
        return self.author.login

class Tag(models.Model):
    post = models.ManyToManyField(Post)
    tag = models.CharField(max_length=255)

class Connection(models.Model):
    post = models.ForeignKey(Post)
    user = models.ManyToManyField(Person)
    text = models.TextField(max_length=255, blank=True, null=True)
    type = models.IntegerField(default=0)

class Place(models.Model):
    id = models.TextField(max_length=255, primary_key=True, unique=True)
    name = models.TextField(max_length=80)
    checkins = models.IntegerField()

class Tip(models.Model):
    id = models.TextField(max_length=255, primary_key=True, unique=True)
    author = models.ForeignKey(Person)
    place = models.ForeignKey(Place)
    text = models.TextField(max_length=80)
    dateOfCreation = models.DateTimeField()

#class Photo(models.Model):
    #id = models.TextField(max_length=255, primary_key=True, unique=True)
    #author = models.ForeignKey(Person)
    #place = models.ForeignKey(Place)
    #photo = models.CharField(max_length=255)
    #dateOfCreation = models.DateTimeField()

beholder/apps/core/views.py
from django.db.models import F, Count
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.views.generic import TemplateView,View, DetailView, ListView
from core.FlickrSearch import FlickrSearch
from core.FoursquareSearch import FoursquareSearch
from core.models import Person, Post, Tag, Connection
from core.InstaSearch import *
from core.TwitterSearch import *
from beholder import settings
import json
import time
import random
import requests

# Create your views here.
class Index(TemplateView):
    template_name = "index.html"

class Auth(View):
    client_id = settings.INSTAGRAM_CLIENT_ID
    client_secret = settings.INSTAGRAM_CLIENT_SECRET
    redirect_uri = settings.INSTAGRAM_REDIRECT_URI

    def get(self, request, *args, **kwargs):
        url = "https://api.instagram.com/oauth/authorize/?client_id=%s&redirect_uri=%s&response_type=code" %(
            self.client_id, self.redirect_uri)

        return HttpResponseRedirect(url)

class Finder(View):

    def get(self, requests, *args, **kwargs):
        code = requests.GET.get('code', None)
        return render(self.request, "finder.html", {"code": code})

    def clear_tables(self):
        Connection.objects.all().delete()
        Tag.objects.all().delete()
        Post.objects.all().delete()
        Person.objects.all().delete()
        Tip.objects.all().delete()
        Place.objects.all().delete()
        print('[+] Tables cleared !')

    def post(self, request, *args, **kwargs):
        code = request.POST.get('code', None)
        lat = request.POST.get('latitude', None)
        lng = request.POST.get('longitude', None)
        posts = request.POST.get('posts', None)
        radius = request.POST.get('radius', None)

        #TODO: Criar um novo projeto para cada busca
        self.clear_tables()

        try:
            insta = InstaSearch()
            insta.search(code, lat, lng, int(posts), radius)
        except Exception as e:
            print("Error in Instagram Search !!")
            print(e)

        print('-' * 30)

        try:
            flickr = FlickrSearch()
            flickr.search(lat, lng, int(posts), int(radius))
        except Exception as e:
            print("Error in Flickr Search !!")
            print(e)

        print('-' * 30)

        try:
            twitter = TwitterSearch()
            twitter.search(lat, lng, int(posts), int(radius))
        except Exception as e:
            print("Error in Twitter Search !!")
            print(e)

        print('-' * 30)

        try:
            fs = FoursquareSearch()
            fs.search(lat, lng, radius)
        except Exception as e:
            print("Error in Foursquare Search !!")
            print(e)

        return HttpResponseRedirect("/posts")

class GetUser(ListView):
    model = Post
    template_name = "List.html"

    def get_queryset(self):
        self.author = get_object_or_404(Person, login = self.args[0])
        return Post.objects.filter(author = self.author).order_by('-dateOfCreation')

class ShowPosts(ListView):
    model = Post
    template_name = "Posts.html"

    def get_queryset(self):
        return Post.objects.order_by('-dateOfCreation')

class ShowNetworks(ListView):
    model = Tag
    template_name = "Networks.html"

    def get_queryset(self):
        return Post.objects.all().values('network').annotate(total = Count('network')).order_by('-total')

class ShowPostsPerNetwork(ListView):
    model = Post
    template_name = "PostPerNetwork.html"

    def get_queryset(self):
        return Post.objects.filter(network = self.args[0]).order_by('-dateOfCreation')

class ShowUsers(ListView):
    model = Person
    template_name = "Users.html"

    def get_queryset(self):
        return Person.objects.annotate(num_posts = Count("post")).order_by('-num_posts')#[:3]

class ShowTags(ListView):
    model = Tag
    template_name = "Tags.html"

    def get_queryset(self):
        return Tag.objects.all().values('tag').annotate(total = Count('tag')).order_by('-total')

class ShowTagsPerUser(ListView):
    model = Tag
    template_name = "TagsPerUser.html"

    def get_queryset(self):
        self.author = get_object_or_404(Person, login = self.args[0])
        post = Post.objects.filter(author = self.author)
        return Tag.objects.all().filter(post = post).values('tag').annotate(total = Count('tag')).order_by('-total')
        
class ShowPostsPerTag(ListView):
    model = Post
    template_name = "PostPerTag.html"

    def get_queryset(self):
        tags = Tag.objects.all().filter(tag = self.args[0])
        return Post.objects.filter(tag = tags).order_by('-dateOfCreation')

class ShowConnectionsFromUser(ListView):
    model = Person
    template_name = "ConnectionsFromUser.html"

    def get_queryset(self):
        person = get_object_or_404(Person, login = self.args[0])
        return Connection.objects.filter(user = person)

class ShowPlaces(ListView):
    model = Place
    template_name = "Places.html"

    def get_queryset(self):
        return Place.objects.all().order_by('-checkins')

class ShowTips(ListView):
    model = Tip
    template_name = 'Tips.html'

    def get_queryset(self):
        place = get_object_or_404(Place, id = self.args[0])
        return Tip.objects.filter(place = place).order_by('-dateOfCreation')

class ShowGraph(ListView):
    model = Connection
    template_name = "Graph.html"

    def get_queryset(self):
        return Connection.objects.all()

beholder/apps/core/templates/ConnectionsFromUser.html
{% load static from staticfiles %}
{% include "header.html" %}
<div class="main">

	<!-- TimeLine -->
	<section class="timeline" id="timeline">

		<!-- page background -->
		<div class="img-background">
			<img src="{% static "source/img/bg-timeline.jpg" %}" alt="Beholder timeline">
		</div>

		<div class="container">

			<!-- content -->
			<div class="timeline-content">

				<!-- title -->
				<div class="title-content">
					<h3>TimeLine</h3>
					<div class="line-timeline">
						<span class="line"></span>
					</div>
				</div>

				<!-- posts -->
				<div class="timeline-post">

					<!-- wgt post -->
                    {% for connection in object_list %}
                        <!-- icon elipse -->
                        <div class="icon-timeline">
	                        <!-- line -->
	                        <div class="line-timeline">
		                        <span class="line"></span>
	                        </div>
                        </div>

                        <div class="user">

	                    <!-- description -->
	                    <div class="post-description">

		                    <!-- photografy -->
		                    <div class="user-photo">
			                    <img src="{{ connection.post.author.profile_picture }}" width="60px" height="60px">
			                    <div class="number-photos">
				                    {% if connection.post.network == "Instagram" %}
				                        <p><span class="fa fa-instagram"></span></p>
                                    {% elif connection.post.network == "Flickr" %}
				                        <p><span class="fa fa-flickr"></span></p>
                                    {% else %}
                                        <p><span class="fa fa-twitter"></span></p>
                                    {% endif %}
			                    </div>
		                    </div>

		                    <!-- Date & Hour -->
		                    <div class="user-post">
			                    <h2>@{{ connection.post.author.login }}</h2>
			                    <h3>{{ connection.post.dateOfCreation }}</h3>
			                    <div class="post-content">
				                    <p>
					                {{ connection.post.text }}
				                    </p>
			                    </div>
		                    </div>
	                    </div>

	                    <!-- Post -->
	                    <div class="photografy-post">
                            {% if connection.post.network == "Twitter" %}
                                <img class="img-responsive" src="{% static "source/img/twitter.png" %}" width="240px" height="240px" alt="Post">
                            {% else %}
		                        <img class="img-responsive" src="{{ connection.post.photo }}" width="240px" height="240px" alt="Post">
                            {% endif %}
	                    </div>
                    </div>
                    {% endfor %}

				</div>
			</div>
		</div>
	</section>

</div>
{% include "footer.html" %}

beholder/apps/core/templates/Graph.html
{% load static from staticfiles %}
{% include "header.html" %}

<!-- main -->
<div class="main">

	<!-- conections -->
	<section class="conections" id="conections">

		<!-- page background -->
		<div class="img-background">
			<img src="{% static "source/img/bg-home.jpg" %}" alt="Beholder timeline">
		</div>

		<div class="container">

			<!-- DIV CENTRALIZADA -->
			<!-- DIV CENTRALIZADA -->
			<!-- DIV CENTRALIZADA -->

			<div class="conections-content" id="conections-content">
				<p>div centralizada</p>
			</div>

			<!-- DIV CENTRALIZADA -->
			<!-- DIV CENTRALIZADA -->
			<!-- DIV CENTRALIZADA -->
            <script src="{% static "js/main-head.js" %}"></script>
            <script src="{% static "source/js/lib/modernizr.custom.js" %}"></script>

            <script src="http://visjs.org/dist/vis.js"></script>
            <link href="http://visjs.org/dist/vis.css" rel="stylesheet" type="text/css">
            <script type="text/javascript">
                var nodes = null;
                var edges = null;
                var network = null;

                function draw() {
                    users = {};
                    sizes = {};
                    edges = [];

                    {% for connection in object_list %}
                        users["{{ connection.post.author.login }}"] = "{{ connection.post.author.profile_picture }}";
                        if (sizes.hasOwnProperty("{{ connection.post.author.login }}")) {
                            sizes["{{ connection.post.author.login }}"] += {{ connection.user.count }} * 20;
                        } else {
                            sizes["{{ connection.post.author.login }}"] = {{ connection.user.count }} * 20;
                        }
                        {% for user in connection.user.all %}
                            {% if user.post_set.count > 0 %}
                                users["{{ user.login }}"] = "{{ user.profile_picture }}";
                                edges.push({from: "{{ user.login }}", to: "{{ connection.post.author.login }}", arrows:'to', width: 3});
                            {% endif %}
                        {% endfor %}
                    {% endfor %}

                    nodes = [];
                    Object.keys(users).forEach(function (key) {
                        if (sizes[key]) {
                            nodes.push({id: key,  shape: 'circularImage', image: users[key], label: key, value: sizes[key]});
                        } else {
                            nodes.push({id: key,  shape: 'circularImage', image: users[key], label: key, value: 20});
                        }
                    });

                    // create a network
                    var container = document.getElementById('conections-content');
                    var data = {
                        nodes: nodes,
                        edges: edges
                    };
                    var options = {
                        nodes: {
                            size:60,
                            font:{color:'#000000', size:20}
                        },
                        edges: {
                            color: '#31B404'
                        }
                    };
                    network = new vis.Network(container, data, options);
                }

                draw();
            </script>

		</div>

	</section>

</div>

{% include "footer.html" %}

beholder/apps/core/templates/List.html
{% load static from staticfiles %}
{% include "header.html" %}
<div class="main">

	<!-- TimeLine -->
	<section class="timeline" id="timeline">

		<!-- page background -->
		<div class="img-background">
			<img src="{% static "source/img/bg-timeline.jpg" %}" alt="Beholder timeline">
		</div>

		<div class="container">

			<!-- content -->
			<div class="timeline-content">

				<!-- title -->
				<div class="title-content">
					<h3>TimeLine</h3>
					<div class="line-timeline">
						<span class="line"></span>
					</div>
				</div>

				<!-- posts -->
				<div class="timeline-post">

					<!-- wgt post -->
                    {% for post in object_list %}
                        <!-- icon elipse -->
                        <div class="icon-timeline">
	                        <!-- line -->
	                        <div class="line-timeline">
		                        <span class="line"></span>
	                        </div>
                        </div>

                        <div class="user">

	                    <!-- description -->
	                    <div class="post-description">

		                    <!-- photografy -->
		                    <div class="user-photo">
			                    <img src="{{ post.author.profile_picture }}" width="60px" height="60px">
			                    <div class="number-photos">
				                    {% if post.network == "Instagram" %}
				                        <p><span class="fa fa-instagram"></span></p>
                                    {% elif post.network == "Flickr" %}
                                        <p><span class="fa fa-flickr"></span></p>
                                    {% else %}
                                        <p><span class="fa fa-twitter"></span></p>
                                    {% endif %}
			                    </div>
		                    </div>

		                    <!-- Date & Hour -->
		                    <div class="user-post">
			                    <h2>@{{ post.author.login }}</h2>
			                    <h3>{{ post.dateOfCreation }}</h3>
			                    <div class="post-content">
				                    <p>
					                {{ post.text }}
				                    </p>
			                    </div>
		                    </div>
	                    </div>

	                    <!-- Post -->
	                    <div class="photografy-post">
                            {% if post.network == "Twitter" %}
                                <img class="img-responsive" src="{% static "source/img/twitter.png" %}" width="240px" height="240px" alt="Post">
                            {% else %}
		                        <img class="img-responsive" src="{{ post.photo }}" width="240px" height="240px" alt="Post">
                            {% endif %}
	                    </div>
                    </div>
                    {% endfor %}

				</div>
			</div>
		</div>
	</section>

</div>
{% include "footer.html" %}

beholder/apps/core/templates/Networks.html
{% load static from staticfiles %}
{% include "header.html" %}
<div class="main">

	<!-- top tags -->
	<section class="top-tags" id="top-tags">

		<!-- page background -->
		<div class="img-background">
			<img src="{% static "source/img/bg-tops.jpg" %}" alt="Beholder topusers">
		</div>

		<div class="container">
			<div class="top-tags-content">

				<!-- title -->
				<div class="title-content">
					<h3>Top Networks</h3>
				</div>

                {% for post in object_list %}
				    <!-- wgt -->
                    <div class="wgt-tag">
                    	<!-- tag position  -->
	                    <div class="tag-position">
		                    <p>#{{ forloop.counter }}</p>
	                    </div>
                    	<!-- tag description -->
	                    <div class="tag-description">
		                    <h4><a href="/networks/{{ post.network }}/">{{ post.network }}</a></h4>
		                    {% if post.total == 1 %}
                                <p>{{ post.total }} Publication</p>
                            {% else %}
                                <p>{{ post.total }} Publications</p>
                            {% endif %}
	                    </div>
                    </div>
				{% endfor %}

			</div>
		</div>
	</section>

</div>
{% include "footer.html" %}

beholder/apps/core/templates/PostPerNetwork.html
{% load static from staticfiles %}
{% include "header.html" %}
<div class="main">

	<!-- TimeLine -->
	<section class="timeline" id="timeline">
		
		<!-- page background -->
		<div class="img-background">
			<img src="{% static "source/img/bg-timeline.jpg" %}" alt="Beholder timeline">
		</div>

		<div class="container">
			
			<!-- content -->
			<div class="timeline-content">
				
				<!-- title -->
				<div class="title-content">
					<h3>TimeLine</h3>
					<div class="line-timeline">
						<span class="line"></span>
					</div>
				</div>
				
				<!-- posts -->
				<div class="timeline-post">

					<!-- wgt post -->
                    {% for post in object_list %}
                        <!-- icon elipse -->
                        <div class="icon-timeline">
	                        <!-- line -->
	                        <div class="line-timeline">
		                        <span class="line"></span>
	                        </div>
                        </div>

                        <div class="user">

	                    <!-- description -->
	                    <div class="post-description">

		                    <!-- photografy -->
		                    <div class="user-photo">
			                    <img src="{{ post.author.profile_picture }}" width="60px" height="60px">
			                    <div class="number-photos">
                                    {% if post.network == "Instagram" %}
				                        <p><span class="fa fa-instagram"></span></p>
                                    {% elif post.network == "Flickr" %}
                                        <p><span class="fa fa-flickr"></span></p>
                                    {% else %}
                                        <p><span class="fa fa-twitter"></span></p>
                                    {% endif %}
			                    </div>
		                    </div>

		                    <!-- Date & Hour -->
		                    <div class="user-post">
			                    <h2>@{{ post.author.login }}</h2>
			                    <h3>{{ post.dateOfCreation }}</h3>
			                    <div class="post-content">
				                    <p>
					                {{ post.text }}
				                    </p>
			                    </div>
		                    </div>
	                    </div>

	                    <!-- Post -->
	                    <div class="photografy-post">
                            {% if post.network == "Twitter" %}
                                <img class="img-responsive" src="{% static "source/img/twitter.png" %}" width="240px" height="240px" alt="Post">
                            {% else %}
		                        <img class="img-responsive" src="{{ post.photo }}" width="240px" height="240px" alt="Post">
                            {% endif %}
	                    </div>
                    </div>
                    {% endfor %}

				</div>
			</div>
		</div>
	</section>

</div>
{% include "footer.html" %}

beholder/apps/core/templates/PostPerTag.html
{% load static from staticfiles %}
{% include "header.html" %}
<div class="main">

	<!-- TimeLine -->
	<section class="timeline" id="timeline">

		<!-- page background -->
		<div class="img-background">
			<img src="{% static "source/img/bg-timeline.jpg" %}" alt="Beholder timeline">
		</div>

		<div class="container">

			<!-- content -->
			<div class="timeline-content">

				<!-- title -->
				<div class="title-content">
					<h3>TimeLine</h3>
					<div class="line-timeline">
						<span class="line"></span>
					</div>
				</div>

				<!-- posts -->
				<div class="timeline-post">

					<!-- wgt post -->
                    {% for post in object_list %}
                        <!-- icon elipse -->
                        <div class="icon-timeline">
	                        <!-- line -->
	                        <div class="line-timeline">
		                        <span class="line"></span>
	                        </div>
                        </div>

                        <div class="user">

	                    <!-- description -->
	                    <div class="post-description">

		                    <!-- photografy -->
		                    <div class="user-photo">
			                    <img src="{{ post.author.profile_picture }}" width="60px" height="60px">
			                    <div class="number-photos">
				                    {% if post.network == "Instagram" %}
				                        <p><span class="fa fa-instagram"></span></p>
                                    {% elif post.network == "Flickr" %}
                                        <p><span class="fa fa-flickr"></span></p>
                                    {% else %}
                                        <p><span class="fa fa-twitter"></span></p>
                                    {% endif %}
			                    </div>
		                    </div>

		                    <!-- Date & Hour -->
		                    <div class="user-post">
			                    <h2>@{{ post.author.login }}</h2>
			                    <h3>{{ post.dateOfCreation }}</h3>
			                    <div class="post-content">
				                    <p>
					                {{ post.text }}
				                    </p>
			                    </div>
		                    </div>
	                    </div>

	                    <!-- Post -->
	                    <div class="photografy-post">
                            {% if post.network == "Twitter" %}
                                <img class="img-responsive" src="{% static "source/img/twitter.png" %}" width="240px" height="240px" alt="Post">
                            {% else %}
		                        <img class="img-responsive" src="{{ post.photo }}" width="240px" height="240px" alt="Post">
                            {% endif %}
	                    </div>
                    </div>
                    {% endfor %}

				</div>
			</div>
		</div>
	</section>

</div>
{% include "footer.html" %}

beholder/apps/core/templates/Posts.html
{% load static from staticfiles %}
{% include "header.html" %}
<div class="main">

	<!-- TimeLine -->
	<section class="timeline" id="timeline">
		
		<!-- page background -->
		<div class="img-background">
			<img src="{% static "source/img/bg-timeline.jpg" %}" alt="Beholder timeline">
		</div>

		<div class="container">
			
			<!-- content -->
			<div class="timeline-content">
				
				<!-- title -->
				<div class="title-content">
					<h3>TimeLine</h3>
					<div class="line-timeline">
						<span class="line"></span>
					</div>
				</div>
				
				<!-- posts -->
				<div class="timeline-post">

					<!-- wgt post -->
                    {% for post in object_list %}
                        <!-- icon elipse -->
                        <div class="icon-timeline">
	                        <!-- line -->
	                        <div class="line-timeline">
		                        <span class="line"></span>
	                        </div>
                        </div>

                        <div class="user">

	                    <!-- description -->
	                    <div class="post-description">

		                    <!-- photografy -->
		                    <div class="user-photo">
			                    <img src="{{ post.author.profile_picture }}" width="60px" height="60px">
			                    <div class="number-photos">
                                    {% if post.network == "Instagram" %}
				                        <p><span class="fa fa-instagram"></span></p>
                                    {% elif post.network == "Twitter" %}
                                        <p><span class="fa fa-twitter"></span></p>
                                    {% else %}
                                        <p><span class="fa fa-flickr"></span></p>
                                    {% endif %}
			                    </div>
		                    </div>

		                    <!-- Date & Hour -->
		                    <div class="user-post">
			                    <h2>@{{ post.author.login }}</h2>
			                    <h3>{{ post.dateOfCreation }}</h3>
			                    <div class="post-content">
				                    <p>
					                {{ post.text }}
				                    </p>
			                    </div>
		                    </div>
	                    </div>

	                    <!-- Post -->
	                    <div class="photografy-post">
                            {% if post.network == "Twitter" %}
                                <img class="img-responsive" src="{% static "source/img/twitter.png" %}" width="240px" height="240px" alt="Post">
                            {% else %}
		                        <img class="img-responsive" src="{{ post.photo }}" width="240px" height="240px" alt="Post">
                            {% endif %}
	                    </div>
                    </div>
                    {% endfor %}

				</div>
			</div>
		</div>
	</section>

</div>
{% include "footer.html" %}

beholder/apps/core/templates/Users.html
{% load static from staticfiles %}
{% include "header.html" %}
<div class="main">

	<!-- top Users -->
	<section class="top-users" id="top-users">

		<!-- page background -->
		<div class="img-background">
			<img src="{% static "source/img/bg-tops.jpg" %}" alt="BeHolder topusers">
		</div>

		<div class="container">
			<div class="top-users-content">

				<!-- title -->
				<div class="title-content">
					<h3>Top Users</h3>
				</div>

                {% for user in object_list %}
				<!-- wgt -->
                    {% if user.post_set.count > 0 %}
                        <div class="wgt-user">
        	                <!-- user position  -->
	                        <div class="user-position">
		                        <p>#{{ forloop.counter }}</p>
	                        </div>

	                        <!-- photografy -->
	                        <div class="user-photo">
		                        <img src="{{ user.profile_picture }}" width="60px" height="60px">
		                        <div class="number-photos">
			                        <p>{{ user.post_set.count }}</p>
		                        </div>
                    	    </div>

	                        <!-- user description -->
	                        <div class="user-description">
		                        <h4><a href="/users/{{ user.login }}/">@{{ user.login }}</a></h4>
		                        <p>{{ user.name }}</p>
		                        {% if user.post_set.count == 1 %}
                                    <p>{{ user.post_set.count }} publication</p>
                                {% elif user.post_set.count > 1 %}
                                    <p>{{ user.post_set.count }} publications</p>
                                {% endif %}
                                {% if user.connection_set.count == 1 %}
                                    <p><a href="/connections/from/{{ user.login }}/">{{ user.connection_set.count }} connection</a></p>
                                {% elif user.connection_set.count > 1 %}
                                    <p><a href="/connections/from/{{ user.login }}/">{{ user.connection_set.count }} connections</a></p>
                                {% endif %}
                                <p><a href="/tags/from/{{ user.login }}/">User top tags</a></p>
	                        </div>
                        </div>
                    {% endif %}
				{% endfor %}

			</div>
		</div>
	</section>

</div>
{% include "footer.html" %}

beholder/apps/core/templates/index.html
{% load static from staticfiles %}
<html>
<title>BEHOLDER - SN</title>

BEHOLDER-NG OSINT
<p></p>

<a href="/auth">
    <img src="{% static "source/img/instagram-login-button.png" %}">
</a>


</html>